version: '3.3'

services:
  app:
    container_name: dtech-app
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - APP_HOST=0.0.0.0
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command:
      /bin/bash -c """
      python launcher.py init-database &&
      python launcher.py create-superuser -n admin -p password &&
      python launcher.py runserver
      """
  postgres:
    container_name: dtech-postgres
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}

networks:
  default:
    driver: bridge